### ISSUE TITLE
Error: failed to connect

### ISSUE THREAD

**Issue by diwalker** [tungtouch/HubTaxi-Server#9]
Mongo running normally, but when I run npm start in the folder, this error appears just below, and http: // localhost: 6868 does not open, but the mongo is running. I'd like some help to find out why.

npm start

> vframework@0.0.1 start /home/dking/Documentos/HubTaxi-Server
> node server

connect.multipart() will be removed in connect 3.0
visit https://github.com/senchalabs/connect/wiki/Connect-3.0 for alternatives
connect.limit() will be removed in connect 3.0
connection error: Error: failed to connect to [localhost:27017]
    at exports.ConnectionPool.<anonymous> (/home/dking/Documentos/HubTaxi-Server/node_modules/mongodb/lib/mongodb/connection/server.js:540:25)
    at exports.ConnectionPool.emit (events.js:182:13)
    at exports.ConnectionPool.EventEmitter.emit (domain.js:442:20)
    at exports.Connection.<anonymous> (/home/dking/Documentos/HubTaxi-Server/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:140:15)
    at exports.Connection.emit (events.js:182:13)
    at exports.Connection.EventEmitter.emit (domain.js:442:20)
    at Socket.<anonymous> (/home/dking/Documentos/HubTaxi-Server/node_modules/mongodb/lib/mongodb/connection/connection.js:478:10)
    at Socket.emit (events.js:182:13)
    at Socket.EventEmitter.emit (domain.js:442:20)
    at emitErrorNT (internal/streams/destroy.js:82:8)

**Comment by Sphinix1** [comment]
were you able to resolve this
same issue here
'
